version: "2"

services:
  postgres:
    image: 'postgres:10.3'
    env_file:
      - '.env'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    ports:
      - '5432:5432'

  web:
    build: .
    command: >
      gunicorn -c "python:config.gunicorn"
        --reload
        "ids.app:create_app()"
    env_file:
      - ".env"
    ports:
      - "8000:8000"
    volumes:
      - ".:/app"


volumes:
  postgres:
